name: poc_login
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.10
  riverpod_annotation: ^2.1.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^10.1.2
  image_picker: ^1.0.4
  file_picker: ^5.5.0
  validatorless: ^1.2.3
  intl: ^0.18.1
  url_launcher: ^6.1.14
  dio: ^5.3.2
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.3
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  
flutter:
  uses-material-design: true
